### ISSUE TITLE
New acronym

### ISSUE THREAD

**Issue by Asteria31** [MitanshiKshatriya/ts-acronyms#1]
Petition to add ATW10MVTVFTVSGAVRALPS:
All Too Well (10 Minute Version) (From The Vault) (Taylor's Version) (Sad Girl Autumn Version) - Recorded At Long Pond Studios
I'm new to GitHub so if this is the wrong way to ask, I apologise

**Comment by MitanshiKshatriya** [comment]
Sure would love to add this one.
Sorry I missed the notification for the issue 😬

Would you like to do a pull request for this?

**Comment by Asteria31** [comment]
I don't really know how to do that, to be honest 😅
I also noticed there aren't any acronyms for midnights, if you could please
add them too.

**Comment by JasyJasRoc16** [comment]
Bdilh is but daddy i love him

**Comment by MitanshiKshatriya** [comment]
I will add the acronyms this weekend 🫶

**Comment by MitanshiKshatriya** [comment]
updated, thanks
